### ISSUE TITLE
【依頼】フリマアプリ挙動確認

### ISSUE THREAD

**Issue by sora-site** [sora-site/furima-40734#20]
# URL
https://furima-40734.onrender.com/
# 出品者用のメールアドレスとパスワード
メールアドレス：test@test.jp
パスワード：aaa111
# 購入者用のメールアドレスとパスワード
メールアドレス：test2@test.jp
パスワード：aaa111

**Comment by 152867take** [comment]
@sora-site さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]
- [x] 入力された販売価格によって、販売手数料や販売利益が変わるようにしましょう(JavaScriptを使用して実装すること)
※現在商品の出品が失敗すると、それ以降販売手数料及び販売利益が計算されません。

- [x] 商品編集機能の実装をしましょう
※現在商品編集ページに遷移しようとするとエラーが発生します。
※編集機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

- [x] ログイン状態の場合でも、自身が出品していない売却済み商品の商品購入ページへ遷移しようとすると、トップページに遷移するようにしましょう

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by mo1015** [comment]
@sora-site さん、ご提出ありがとうございます‼︎
動作の確認をしたところ、新たに修正していただきたい箇所と、引き続き修正していただきたい箇所がございました。
以下のご確認をお願いします！

[修正依頼箇所]

- [x] **入力された販売価格によって、販売手数料や販売利益が変わること(JavaScriptを使用して実装すること)**
画像のように販売利益が正しく表示されていません。金額が正しく表示されるよう修正しましょう。
<img width="806" alt="スクリーンショット 2024-06-19 9 29 07" src="https://github.com/sora-site/furima-40734/assets/62644781/4bc4792d-af02-4bb6-bb76-e91dca4e36d6">

- [x] **ログイン状態の場合は、自身が出品した販売中商品の商品情報編集ページに遷移できること**
「商品の編集」ボタンを押すと、トップページに遷移してしまいます。
※編集機能に関しては動作確認ができていない為、次回ご提出時に併せて確認させていただきます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう！
修正内容が反映されていることを確認できましたら以下の最終課題完了報告フォームのご提出をお願いします！
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by shodai-ito** [comment]
@sora-site さん、ご提出ありがとうございます!! 
動作の確認をしたところ、修正していただきたい箇所がございました。
以下のご確認をお願いします!

[修正依頼箇所]
**商品編集機能の確認**
- [x] **ログアウト状態の場合は、商品情報編集ページへ遷移しようとすると、商品の販売状況に関わらずログインページに遷移すること**
現在、ログアウト状態で編集ページに遷移しようとすると、トップページに遷移してしまいます。

修正が完了しましたら、一度ご自身の本番環境で正しく動作しているか確認してみましょう。
修正内容が反映されていることが確認できましたら、再度以下の最終課題完了報告フォームのご提出をお願いします!
※新しいissueを作っていただく必要はございません。
※質問等でコメントした場合も都度フォームのご提出をお願いします。
https://forms.gle/dYuR1wjeHepbEhU7A

**Comment by OMG3215** [comment]
@sora-site さん、最終課題「FURIMA」の開発、お疲れ様です。

ご提出いただいたアプリケーションについて、正常に動作することを確認いたしました。
達成要件を満たしましたので、完了認定（LGTM）とさせていただきます。おめでとうございます!!

_※ スタッフ側で実施した動作確認は必須機能についてのみです。追加機能についての動作確認は実施しておりません。追加機能を実装した場合は想定通りの挙動となっているか自分自身で確認をお願い致します。_
_※ Github上の最終課題の履歴はここまで頑張ってきたことの証となります。削除せず大切に保管するようにしましょう。_

![lgtm_01](https://user-images.githubusercontent.com/54050089/186354234-2de2a3d1-500d-4164-81d5-7585cdd03227.png)
